# Generated by Django 4.0.6 on 2022-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KilimoDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('subcounty', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=255)),
                ('element', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('items', models.CharField(max_length=255)),
            ],
        ),
    ]
