# Generated by Django 4.0.6 on 2022-08-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0002_kilimodomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilimodomains',
            name='value',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
