# Generated by Django 4.0.6 on 2022-09-03 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kilimodata', '0003_kilimodomains_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSpecify',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('itemcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kilimodata.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KilimoData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcounty', models.CharField(max_length=256, null=True)),
                ('ward', models.CharField(max_length=256, null=True)),
                ('value', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kilimodata.county')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kilimodata.domain')),
                ('elements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.elements')),
                ('itemspecify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.itemspecify')),
                ('registeredby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kilimodata.sector')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kilimodata.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('registeredby', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataEntryOfficer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nationalid', models.CharField(max_length=256, null=True)),
                ('firstname', models.CharField(max_length=256, null=True)),
                ('lastname', models.CharField(max_length=256, null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=256, null=True)),
                ('designation', models.CharField(max_length=256, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.institution')),
                ('registeredby', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
