# Generated by Django 4.0.6 on 2022-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0004_county_domain_elements_itemcategory_itemspecify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentryofficer',
            name='registeredby',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='registeredby',
        ),
        migrations.RemoveField(
            model_name='kilimodata',
            name='registeredby',
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataentryofficer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemspecify',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
