# Generated by Django 4.0.6 on 2022-09-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0005_remove_dataentryofficer_registeredby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilimodata',
            name='refyear',
            field=models.IntegerField(null=True),
        ),
    ]
