# Generated by Django 4.0.6 on 2022-09-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0006_kilimodata_refyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.domain'),
        ),
    ]
