# Generated by Django 4.0.6 on 2022-09-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0007_subdomain_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kilimodata',
            name='domain',
        ),
    ]
