# Generated by Django 4.0.6 on 2022-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0008_remove_kilimodata_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
