# Generated by Django 4.0.6 on 2022-09-03 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0010_unit_kilimodata_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilimodata',
            name='refyear',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2090)]),
        ),
    ]
