# Generated by Django 4.0.6 on 2022-09-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0011_alter_kilimodata_refyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilimodata',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
