# Generated by Django 4.0.4 on 2022-09-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0012_kilimodata_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.CharField(blank=True, max_length=256, null=True)),
                ('lng', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('loccode', models.CharField(blank=True, max_length=256, null=True)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilimodata.county')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.CharField(blank=True, max_length=256, null=True)),
                ('lng', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('loccode', models.CharField(blank=True, max_length=256, null=True)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilimodata.county')),
                ('subcounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kilimodata.subcounty')),
            ],
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='subcounty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.subcounty'),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.ward'),
        ),
    ]
