# Generated by Django 4.0.4 on 2022-09-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kilimodata', '0013_subcounty_ward_alter_kilimodata_subcounty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilimodata',
            name='refmonth',
            field=models.CharField(blank=True, default='Jan', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='county',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.county'),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.subcounty'),
        ),
        migrations.AlterField(
            model_name='kilimodata',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kilimodata.ward'),
        ),
    ]
